
from gym_cog_ml_tasks.envs.ax_tasks.ax_12_env import AX_12_ENV
from gym_cog_ml_tasks.envs.ax_tasks.ax_cpt_env import AX_CPT_ENV
from gym_cog_ml_tasks.envs.ax_tasks.ax_s_12_env import AX_S_12_ENV
from gym_cog_ml_tasks.envs.ax_tasks.ax_12_cpt_env import AX_12_CPT_ENV
from gym_cog_ml_tasks.envs.task_seq_prediction.seq_prediction_env import seq_prediction_ENV

from gym_cog_ml_tasks.envs.copy_tasks.simple_copy_env import Simple_Copy_ENV
from gym_cog_ml_tasks.envs.copy_tasks.simple_copy_repeat_env import Simple_Copy_Repeat_ENV